
service: serverless-mailer

provider:
  name: aws
  runtime: nodejs4.3

functions:
  mailer:
    handler: handler.mailer
    timeout: 3
    events:
      - http:
          path: email
          method: post
          cors: true
